ssh_command: ssh -i /root/.ssh/backups_rsa

source_directories:
    - /data/backups
    - /var/lib/docker/volumes/
    - /var/lib/docker/containers/*/*.log

keep_daily: 7
keep_weekly: 4
keep_monthly: 6
keep_yearly: 1
