# Using containers means the hostname might change, so it's better to hard-code instead
# of using the Borg placeholder '{hostname}'.
# This applies to archive_name_format and in the repository path
archive_name_format: '${HOSTNAME}-main-{now}'

repositories:
    - path: "ssh://user@host:23/./${HOSTNAME}-main.borg"
      label: main
encryption_passphrase: "A VERY VERY LONG AND COMPLICATED PASSPHRASE"
ssh_command: ssh -i /root/.ssh/id_borgmatic

source_directories:
    - /data/backups
    - /var/lib/docker/volumes/
    - /var/lib/docker/containers/*/*.log
    - /data/app-something/data/db/backups
    # - /data/app-http-logger/data/logs
    # - /data/app-http-logger/data/encrypted
    # - /data/app-http-logger/data/compressed

# before_backup:
    # - /data/useful-scripts/virtuoso-backup.sh <container>
    # - /data/useful-scripts/virtuoso-backup.sh <another_container>
# after_backup:
    # - find /data/app-http-logger/data/logs -type f -delete

on_error:
    - echo "Error while creating a backup."

# By default, we consider being in append-only mode. If this is the case, we should disable
# compacting and pruning. If not in append-only mode, set keep_* variables instead.
skip_actions:
    - compact
    - prune
# keep_daily: 7
# keep_weekly: 4
# keep_monthly: 6
# keep_yearly: 1
# keep_within: 5y

# Borgmatic also provides special hooks for common databases. These have the advantage
# that the dumps are streamed to the backup using a pipe, so they won't use space on
# the host.
# postgresql_databases:
    # - name: all, or name of a particular database
      # hostname: this can be a container name
      # port: exposed container port on the host
      # username: superuser for the database
      # password: superuser's password
      # # if the host doesn't have a dump command:
      # pg_dump_command: docker exec pg_container pg_dump
      # # if the host doesn't have a restore command:
      # pg_restore_command: docker exec pg_container pg_restore
# mariadb_databases:
    # - name: all, or name of a particular database
      # hostname: this can be a container name
      # port: exposed container port on the host
      # username: connection user for the database
      # password: connection user's password
      # # if the host doesn't have a dump command:
      # mariadb_dump_command: docker exec mariadb_container mariadb-dump
