<<: !include /etc/borgmatic/config.base.yaml

source_directories:
    - /data/backups

repositories:
    - path: "ssh://user@host:23/./{hostname}.borg"

encryption_passphrase: "A VERY VERY LONG AND COMPLICATED PASSPHRASE"

keep_yearly: 5

# before_backup:
    # - /data/useful-scripts/virtuoso-backup.sh <container>
    # - /data/useful-scripts/backup-hyperledger-fabric-couchdb.sh <container>
# after_backup:
    # - cleanup scripts are also possible

# postgresql_databases:
    # - name: all, or name of a particular database
      # hostname: this can be a container name
      # port: exposed container port on the host
      # username: superuser for the database
      # password: superuser's password
# mysql_databases:
    # - name: all, or name of a particular database
      # hostname: this can be a container name
      # port: exposed container port on the host
      # username: connection user for the database
      # password: connection user's password
