services:
  borgmatic:
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./data/restore:/restore
    security_opt:
      - apparmor:unconfined
      - label:disable
    devices:
      - /dev/fuse:/dev/fuse
