version: '3'
services:
  borgmatic:
    image: ghcr.io/borgmatic-collective/borgmatic:1.8.11
    restart: always
    container_name: borgmatic
    volumes:
      - ./data/borgmatic.d:/etc/borgmatic.d                 # borgmatic config file(s) + crontab.txt
      - ./data/.borgmatic:/root/.borgmatic                  # borgmatic state files
      - ./data/.config/borg:/root/.config/borg              # config and keyfiles
      - ./data/.cache/borg:/root/.cache/borg                # checksums used for deduplication
      - /root/.ssh/id_borgmatic:/root/.ssh/id_borgmatic:ro  # ssh key for remote repositories
      - /root/.ssh/known_hosts:/root/.ssh/known_hosts       # ssh known_hosts file
      - /var/run/docker.sock:/var/run/docker.sock           # docker socket to communicate with other containers
    environment:
      DOCKERCLI: true

  borgmatic-exporter:
    image: ghcr.io/maxim-mityutko/borgmatic-exporter:v0.2.3
    restart: always
    container_name: borgmatic-exporter
    volumes:
      - ./data/borgmatic.d:/etc/borgmatic.d:ro
      - /root/.ssh/id_borgmatic:/root/.ssh/id_borgmatic:ro
      - /root/.ssh/known_hosts:/root/.ssh/known_hosts:ro
    expose:
      - 9996
    environment:
      BORGMATIC_EXPORTER_PORT: 9996
      BORGMATIC_CONFIG: /etc/borgmatic.d/config.yaml
      # Disable cron for this container:
      SUPERCRONIC_EXTRA_FLAGS: "-test"
    networks:
      - proxy
      - default

networks:
  proxy:
    name: letsencrypt_default
    external: true
